name: Build wheel

on:
  pull_request:
    types: [opened, reopened]
  branches:
    - 'dev'

jobs:
  build-upload-wheel:
    
    uses: OpenBMB/BMTrain/.github/workflows/build_whl.yml@workflow
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Up the Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Download distribution files
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
